import { describe, expect, it } from 'vitest';
import { catalog, validateCatalog, roles } from '../../src/domain/catalog';
import { choiceError, dispatch, planError, publicState, revenueRange, roleOrder, setupGame, shuffled } from '../../src/domain/engine';
import { initial, apply, plan, resolve, next } from '../fixtures/helpers';
import { journey } from '../fixtures/reference';
describe('catálogo e comandos', () => {
  it('valida todas as propriedades do catálogo imutável v0.1', () => { expect(() => validateCatalog(catalog)).not.toThrow(); const c = structuredClone(catalog); c.parameters.cooperativeHarvestBonusPerFarmer = -1; expect(() => validateCatalog(c)).toThrow(); });
  it('tem dez instâncias únicas e embaralhamento reproduzível', () => { expect(new Set(shuffled(42)).size).toBe(10); expect(shuffled(42)).toEqual(shuffled(42)); expect(shuffled(43)).not.toEqual(shuffled(42)); });
  it('prepara uma vez inclusive dotação inicial', () => { const s = initial(); expect(s.cash).toEqual({ lia: 9, bento: 9, rosa: 9 }); expect(dispatch(s, { type: 'createGame', id: 'new', expectedRevision: s.revision }).ok).toBe(false); expect(s.cash.rosa).toBe(9); });
  it('rejeita fase, revisão velha e comando repetido', () => { const s = initial(); for (const cmd of [{ type: 'resolveRound' as const, id: 'x', expectedRevision: 0 }, { type: 'startNextRound' as const, id: 'x', expectedRevision: 1 }, { type: 'showSummary' as const, id: 'test-0', expectedRevision: 1 }]) expect(dispatch(s, cmd).ok).toBe(false); });
  it('esconde seed e futuro e alterna coordenação', () => { const s = initial(); const pub = publicState(s); expect(pub).not.toHaveProperty('deck'); expect(pub).not.toHaveProperty('seed'); expect(pub.remaining.reduce((n,e) => n+e.count,0)).toBe(10); expect(roleOrder({ round: 2 })).toEqual(['bento','rosa','lia']); });
  it('confirmações independentes e alterar escolha retira confirmação', () => { let s = plan(initial(), ['reserve','reserve','reserve']); s = apply(s,{type:'selectAction',role:'lia',choice:{action:'A1'}}); expect(s.confirmed).toEqual({lia:false,bento:true,rosa:true}); });
});
describe('economia e condições de fim', () => {
  it('reproduz cinco safras e vitória independente', () => { let s = initial(journey.map(j => j.event)); for (const [i,j] of journey.entries()) { s = resolve(s,j.actions); expect(roles.map(r => s.cash[r])).toEqual(j.cash); expect(s.resilience).toBe(j.resilience); if(i===2) expect(s.history.at(-1)!.accounts.lia.gross).toBe(6); if(i===3) expect(s.history.at(-1)!.accounts.lia.gross).toBe(11); if(i<4) s=next(s); } s=apply(apply(s,{type:'showSummary'}),{type:'finishGame'}); expect(s.phase).toBe('finished'); expect(s.history.at(-1)!.victory).toBe(true); expect(dispatch(s,{type:'startNextRound',id:'illegal',expectedRevision:s.revision}).ok).toBe(false); });
  for (const f of catalog.referenceFixtures) it(`fixture ${f.name}`, () => { const s=resolve(initial([`${f.event}-1`]),roles.map(r=>f.actions[r] as 'reserve'|'A1'|'A3'|'A4'|'G1'|'G4')); expect(roles.map(r=>s.cash[r])).toEqual(f.expected.cash); expect(s.resilience).toBe(f.expected.resilience); });
  it('cooperativa parcial nunca cobra recursos',()=>{const s=plan(initial(),['A4','reserve','G4']);const before=JSON.stringify(s);expect(planError(s)).toContain('incompleta');expect(dispatch(s,{type:'resolveRound',id:'r',expectedRevision:s.revision}).ok).toBe(false);expect(JSON.stringify(s)).toBe(before);});
  it('cooperativa não evita desgaste nem rende ao construir',()=>{const s=resolve(initial(['favorable-1']),['A4','A4','G4']);expect(s.resilience).toBe(4);expect(s.history[0].resilience.wear).toBe(1);const n=next(s);expect(choiceError(n,'lia',{action:'A4'})).toContain('construída');});
  it('instalações duplicadas e papel errado são bloqueados',()=>{const s=next(resolve(initial(['favorable-1']),['A1','A2','G1']));expect(choiceError(s,'lia',{action:'A1'})).toContain('já existe');expect(choiceError(s,'rosa',{action:'A1'})).toContain('papel');});
  it('compras exigem alvo e não financiam ação atual',()=>{const s=initial();expect(choiceError(s,'rosa',{action:'G3'})).toContain('destinatário');s.cash.lia=1;expect(choiceError(s,'lia',{action:'A1'})).toContain('Faltam');const r=resolve(s,['reserve','reserve','G3'],'lia');expect(r.history[0].accounts.lia.transfer).toBe(4);expect(r.cash.rosa).toBe(5);});
  it('proteção excedente não cria receita e limite R só aplica ao final',()=>{const s=initial();s.startResilience=6;s.resilience=6;const r=resolve(s,['A1','A1','G2']);expect(r.history[0].accounts.lia.loss).toBe(0);expect(r.history[0].accounts.lia.revenue).toBe(6);expect(r.resilience).toBe(6);});
  it('limite superior não descarta ganhos antes do evento',()=>{const s=initial();s.startResilience=6;s.resilience=6;const r=resolve(s,['A1','A1','G1']);expect(r.resilience).toBe(6);});
  it('reserva duas vezes causa derrota ambiental no trajeto',()=>{let s=resolve(initial(['drought-1','pests-1']),['reserve','reserve','reserve']);s=resolve(next(s),['reserve','reserve','reserve']);expect(s.cash.lia).toBe(8);expect(s.resilience).toBe(0);expect(s.history[1].outcome).toContain('Resiliência chegou a zero.');expect(()=>next(s)).toThrow();});
  it('caixa insuficiente encerra somente depois de todas as receitas',()=>{const s=initial(['pests-1']);s.cash.lia=0;const r=resolve(s,['reserve','reserve','G1']);expect(r.history[0].outcome.some(x=>x.includes('Lia'))).toBe(true);expect(r.history[0].accounts.bento.after).toBe(10);});
  it('cinco safras sem cooperativa não é vitória',()=>{let s=initial(['favorable-1','fair-1','regular-1','favorable-2','flood-1']);for(let i=0;i<5;i++){s=resolve(s,['reserve','reserve',i===3?'reserve':'G1']);if(i<4)s=next(s);}expect(s.history[4].outcome).toContain('A cooperativa não foi construída.');expect(s.history[4].victory).toBe(false);});
  it('repetir resolução não duplica dinheiro e faixa não olha próxima carta',()=>{const s=plan(initial(),['A1','A3','G1']);const range=revenueRange(s,'lia');const other=structuredClone(s);[other.deck[0],other.deck[6]]=[other.deck[6],other.deck[0]];expect(revenueRange(other,'lia')).toEqual(range);const r=apply(s,{type:'resolveRound'});expect(dispatch(r,{type:'resolveRound',id:'repeat',expectedRevision:r.revision}).ok).toBe(false);expect(r.cash.lia).toBe(9);});
  it('repetir sequência cria recursos novos com gameId distinto',()=>{const s=resolve(initial(),['A1','A3','G1']);const fresh=setupGame('another-id',s.seed,s.deck);expect(fresh.cash.lia).toBe(12);expect(fresh.gameId).not.toBe(s.gameId);expect(fresh.deck).toEqual(s.deck);});
});
