import { expect, it } from 'vitest';
import { clear, keys, load, parseSnapshot, save, type StorageAdapter } from '../../src/persistence/snapshot';
import { initial, apply, resolve, next } from '../fixtures/helpers';
import { journey } from '../fixtures/reference';
import { Store } from '../../src/app/store';
class Memory implements StorageAdapter { data=new Map<string,string>(); getItem(k:string){return this.data.get(k)??null;} setItem(k:string,v:string){this.data.set(k,v);} removeItem(k:string){this.data.delete(k);} }
it('round-trip de todas as fases, escolhas e confirmações',()=>{const states=[initial(journey.map(j=>j.event))];let s=states[0];for(const [i,j] of journey.entries()){s=resolve(s,j.actions);states.push(s);s=apply(s,{type:'showSummary'});states.push(s);s=apply(s,{type:i===4?'finishGame':'startNextRound'});states.push(s);}for(const state of states)expect(parseSnapshot(JSON.stringify(state))).toEqual(state);});
it('rejeita JSON, versão, NaN, baralho duplicado, cursor e histórico adulterado',()=>{expect(()=>parseSnapshot('{')).toThrow();for(const change of [{schemaVersion:8},{cash:{lia:-1,bento:9,rosa:9}},{cursor:3},{deck:Array(10).fill('drought-1')},{resilience:99},{confirmed:{lia:true,bento:false,rosa:false}}]){expect(()=>parseSnapshot(JSON.stringify({...initial(),...change}))).toThrow();}const s=resolve(initial(),['A1','A3','G1']);s.history[0].accounts.lia.revenue++;expect(()=>parseSnapshot(JSON.stringify(s))).toThrow();expect(()=>parseSnapshot('x'.repeat(1048577))).toThrow('1 MB');});
it('recupera cópia anterior válida e preserva dados de outros apps',()=>{const mem=new Memory();const s=initial();expect(save(mem,keys.normal,s).ok).toBe(true);save(mem,keys.normal,apply(s,{type:'selectAction',role:'lia',choice:{action:'A1'}}));mem.setItem(keys.normal,'corrompido');const loaded=load(mem,keys.normal);expect(loaded.recovered).toBe(true);expect(loaded.state).toEqual(s);mem.setItem('other-app','safe');clear(mem);expect(mem.getItem('other-app')).toBe('safe');});
it('quota ou permissão não encerra sessão nem anuncia sucesso',()=>{const mem=new Memory();const store=new Store(mem,keys.normal);store.replace(initial());mem.setItem=()=>{throw new Error('QuotaExceeded');};expect(store.dispatch({type:'selectAction',role:'lia',choice:{action:'A1'}})).toBe(true);expect(store.state?.choices.lia?.action).toBe('A1');expect(store.saved).toBe(false);expect(store.message).toContain('Sem salvamento');});
it('outra aba bloqueia comandos até recarregar',()=>{const mem=new Memory();const store=new Store(mem,keys.normal);store.replace(initial());store.externalChange();expect(store.dispatch({type:'selectAction',role:'lia',choice:{action:'A1'}})).toBe(false);expect(store.replace(initial())).toBe(false);store.reload();expect(store.stale).toBe(false);});
it('tutorial e partida normal ficam isolados',()=>{const mem=new Memory();const s=initial();save(mem,keys.normal,s);save(mem,keys.tutorial,next(resolve(s,['A1','A3','G1'])));expect(load(mem,keys.normal).state).toEqual(s);});
