import type { ActionId } from '../../src/domain/catalog';
// Transcribed from design §11; expected values are not generated by the engine.
export const journey: { actions: [ActionId, ActionId, ActionId]; event: string; cash: number[]; resilience: number }[] = [
  { actions: ['A1', 'A3', 'G1'], event: 'drought-1', cash: [9, 12, 5], resilience: 4 },
  { actions: ['A2', 'A1', 'G1'], event: 'pests-1', cash: [7, 7, 4], resilience: 6 },
  { actions: ['A4', 'A4', 'G4'], event: 'regular-1', cash: [8, 8, 5], resilience: 6 },
  { actions: ['A3', 'A2', 'G2'], event: 'flood-1', cash: [14, 9, 5], resilience: 6 },
  { actions: ['reserve', 'A3', 'reserve'], event: 'favorable-1', cash: [20, 17, 8], resilience: 5 },
];
